### ISSUE TITLE
Binary Ninja [Default]: query_for_cmd() got an unexpected keyword argument 'bv'

### ISSUE THREAD

**Issue by impost0r** [mahaloz/DAILA#17]
This may be an issue with **kwargs. Not sure exactly where it is, though. Currently on Binary Ninja 3.4.4271.

**Comment by impost0r** [comment]
No error now, but no output either. Using the "find vulnerabilities" function.

**Comment by mahaloz** [comment]
@impost0r would you be able to check both the Python console and the normal log for any other errors or output? Also, do the other options work and just not this one? I'll be able to test more this weekend.

**Comment by mahaloz** [comment]
@impost0r fixed it in the linked PR. lmk if you have other issues.
