### ISSUE TITLE
DAILA context-menu does not add in Ghidra on Windows

### ISSUE THREAD

**Issue by velteyn** [mahaloz/DAILA#27]
Hello,
I followed the installation manual but at the end when I installed the plugin on folder

C:\Users\(MY USER)\ghidra_scripts

and enabled the path on ghidra script manager I cannot see the plugin and I cannot enable it !!
Am I missing something ?
Thank you

**Comment by velteyn** [comment]
Ok I installed it manually and it seem installed. I sterted it but NO context DAILA menù appears...
![immagine](https://github.com/mahaloz/DAILA/assets/1019294/2b0abfc8-c25a-44af-9367-e315e67b4670)
![immagine](https://github.com/mahaloz/DAILA/assets/1019294/80ef9e49-e140-4b88-aae7-ef5d0f743dec)

**Comment by mahaloz** [comment]
@velteyn from the looks of the error, it seems like you don't have `dailalib` installed in the Python instance that your Ghidra is trying to access... To confirm, are you running this natively on Windows?

**Comment by mahaloz** [comment]
From your terminal, try and run `python3 -m daila --help`, see if it runs. If you need to run a different command from python to get this to work, like `py3`, please let me know. The line likely causing the error on Windows is this:
https://github.com/mahaloz/DAILA/blob/6ee9792f85032ff9b0de5b76643fb466f92b58c0/dailalib/daila_plugin.py#L25

**Comment by velteyn** [comment]
> @velteyn from the looks of the error, it seems like you don't have `dailalib` installed in the Python instance that your Ghidra is trying to access... To confirm, are you running this natively on Windows?

Yep Native windows 11

**Comment by velteyn** [comment]
![immagine](https://github.com/mahaloz/DAILA/assets/1019294/54baac04-cc5b-4e67-a5ac-e1e665bb458a)

**Comment by mahaloz** [comment]
@velteyn my mistake. Try `python -m dailalib --help`

**Comment by velteyn** [comment]
Mmm strange but  is the installer not installing the module ? I have only this python installed in this machine, nothing more..
I intended that the intaller do anything, Im not a python expert tough

**Comment by velteyn** [comment]
![immagine](https://github.com/mahaloz/DAILA/assets/1019294/01e01bcc-4e48-49f7-88fe-40314b9eadfb)

**Comment by mahaloz** [comment]
@velteyn if you have Discord, we can do back and forth faster over text there if you can join: https://discord.gg/FHVY8yjb.

**Comment by Al-Christodoulou** [comment]
I'm experiencing the same issue, and `dailalib` is installed correctly. I don't know if the `Closing connection` message is supposed to pop up either.
![ghidra](https://github.com/mahaloz/DAILA/assets/99661503/f6d169e7-0551-4ed0-8114-c663a8781561)

**Comment by mahaloz** [comment]
Hi, @Al-Christodoulou. It is good that you see a connection, normally you should see a connection, a disconnection, and one more connection (due to the way things are inited). For some reason, the connection never comes back. I don't have the time right now to debug Windows versions of the tool, but I can give you some advice. If you run it just like you did for this one, wait a few seconds, than go to a terminal and run:
```python3
python3 -m dailalib -s ghidra
```

I expect something should crash from you running that. Post the crash after that.
