### ISSUE TITLE
DAILA install defaults to user directory

### ISSUE THREAD

**Issue by edmcman** [mahaloz/DAILA#29]
At least for Ghidra, DAILA defaults the install to the user directory instead of the `ghidra_scripts` subdirectory.

```
Now installing...

██████   █████  ██ ██       █████      
██   ██ ██   ██ ██ ██      ██   ██     
██   ██ ███████ ██ ██      ███████     
██   ██ ██   ██ ██ ██      ██   ██     
██████  ██   ██ ██ ███████ ██   ██

The Decompiler AI Language Assistant                                                         


Each decompiler/debugger will be prompted for install below. If you would like to skip install for something
you can enter 'n' or just hit enter. Each path prompt has tab path completion.
Enter nothing in each path prompt to get the default listed.

Install for IDA Pro? [y/n]
n
[!] Skipping or failed install for ida... 

Install for Binary Ninja? [y/n]
n
[!] Skipping or failed install for binja... 

Install for Ghidra? [y/n]
y
Ghidra Scripts Path [default = None] (enter nothing to use default): 
 
[+] Installed ghidra to /Users/eschwartz
```

**Comment by mahaloz** [comment]
Now that is a funny bug. The default is showing `None`, which indicates that the `ghidra_scripts` folder does not exist in your install. Is that true? 

Culprit lines:
https://github.com/binsync/libbs/blob/38977fc604d05ee9bd0d8d3cf1d6fc84511c766c/libbs/plugin_installer.py#L212
https://github.com/binsync/libbs/blob/38977fc604d05ee9bd0d8d3cf1d6fc84511c766c/libbs/plugin_installer.py#L178

**Comment by edmcman** [comment]
This was true when I ran the script, yes.

**Comment by mahaloz** [comment]
Hmmmmm, ok. Well, I think it would probably be _ok_ if we created that folder for you, though I don't like the concept.

**Comment by edmcman** [comment]
Complaining is fine too.  But having the files dumped into $HOME was definitely not what I was expecting!

**Comment by mahaloz** [comment]
Ha, fair enough. I would not like that either. Alright, I'll make it create the folder.
