### ISSUE TITLE
Dailalib Full Install Command

### ISSUE THREAD

**Issue by C1KA** [mahaloz/DAILA#47]
While installing dailalib[full] through pip I was required to use single quotes to install the full package.
pip would fail to find any package if the package name did not look like the following:`'dailalib[full]'`.

![Screenshot 2024-07-25 at 10 40 57 AM](https://github.com/user-attachments/assets/328b91be-897e-4e72-90d9-a94608c398a8)

**Comment by mahaloz** [comment]
Just to check @C1KA, is your shell `zsh`?

**Comment by C1KA** [comment]
Yes, sorry for my late response.
I am using zsh on MacOS 13.

**Comment by idan-h** [comment]
Hey, for me it was the exact opposite. I did not find the package with `''`.

I am on windows tho, maybe it's worth putting 2 options out there for the confusion.

**Comment by mahaloz** [comment]
Ok so the problem here is just the shell. Zsh is the special making the `[` illegal in commands. I'm going to update the README to remove that part and just say you gotta figure it out.

**Comment by C1KA** [comment]
Fair enough, lol. I'll recommend just having a small side note for `zsh` users to enclose it in quotes (single or double). Here is nice and simple [Explanation](https://kinopyo.com/en/blog/escape-square-bracket-by-default-in-zsh) that can go with it in case anyone else asks why.
