### ISSUE TITLE
VarBERT not working

### ISSUE THREAD

**Issue by ctusch** [mahaloz/DAILA#53]
Hey, I did a full install and integrated DAILA into Ghidra. But when I tell it to suggest variable names with VarBERT it only logs "Predicting for function ..." and nothing happens afterwards.

DAILA: 3.4.6
VarBERT: 2.2.1
libbs: 1.21.0

I'm on Windows. Maybe there is a verbose mode I can activate?

**Comment by mahaloz** [comment]
Hi @ctusch, to clarify, are you on normal native Windows, or are you using WSL with Ghidra and your Python inside WSL? I'll see if I can reproduce first on the working example.

**Comment by mahaloz** [comment]
Also, is there any chance this binary is sharable? Or if not that, the function text?

**Comment by mahaloz** [comment]
My hunch is this is the line that is halting your predictions (I'll change the log level to be error by default):
https://github.com/binsync/varbert_api/blob/acb1b420f66d4143524fba95cacd8877d13c871b/varbert/api.py#L50

Look at the function and check if:
- there are no function args
- there are no stack args 
- the only args are local args that are all register args

If that is the case, there may be a special fix that I'll need to implement to handle this case.

**Comment by mahaloz** [comment]
Alright, I may have fixed it in #54. Update both varbert and daila:
```
pip install -U varbert dailalib[full]
```

Let me know if it works :)

**Comment by wayland572** [comment]
It's working now, thanks for the fast fix!

**Comment by ctusch** [comment]
It's working now, thanks for the quick fix!
