### ISSUE TITLE
 ghidra.interface | Exception in ctx menu

### ISSUE THREAD

**Issue by AvCPC** [mahaloz/DAILA#62]
Hi, 

I'm running DAILA on linux with ghidra 11.2
Whenever i call a function from contextual menu (eg. summarize) i constantly got this warning (and no result) : 
```
[INFO] | ghidra.interface | Querying summarize prompt with function <Function: int FUN_4065f928(args=2); @0x65f928 vars=9 len=0x684>...
[WARNING] | ghidra.interface | Exception in ctx menu callback summarize: 'NoneType' object has no attribute 'line_number'
```

I'm using gpt4-o model and from what i can tell my API_KEY is properly configured

**Comment by mahaloz** [comment]
@AvCPC update with `pip install -U dailalib`. It should be on `v3.10.1` now, which fixes this issue.
