### ISSUE TITLE
Feature Request: GUI for accessing LLM endpoint and model

### ISSUE THREAD

**Issue by pc9441** [mahaloz/DAILA#66]
As many people are running quite capable self-hosted LLM models, a support for OpenAI-compatible endpoints would be a great addition.
I think something like GhidrOllama could be a good inspiration for this

**Comment by mahaloz** [comment]
We currently use LiteLLM for all of our LLM interactions. Wit this, OpenAI-compatible models are supported: 
https://docs.litellm.ai/docs/providers/openai_compatible 

However, a GUI is currently lacking for users to add their own:
- LLM endoint
— LLM model name

If you’d like, you can convert this issue into a feature request for that GUI

**Comment by pc9441** [comment]
Yes, that would be great

**Comment by mahaloz** [comment]
Closed in #71
